name: Build Nightly Release
on:
  schedule:
    # Run every day at 2:00 AM
    - cron: "0 2 * * *"

jobs:
  build-nightly-release:
    if: github.repository == 'icerpc/icerpc-csharp'
    uses: ./.github/workflows/build-release.yml
    secrets: inherit
    with:
      channel: nightly
      publish: true
